### ISSUE TITLE
Code compact

### ISSUE THREAD

**Issue by akhilsuseelan1996** [sheebashibushazi/testsection1#1]
https://github.com/sheebashibushazi/testsection1/blob/7e9a7ad7ea2357298b6e31b297fb77027623561f/CheckDuplicate.java#L16
This is good! But you can make this a bit more compact and cleaner as shown below.

`
if (mySet.add(myarray[i]) == false)  {
		      System.out.println("The no "+ myarray[i]+" repeated");
		  }
`

**Comment by sheebashibushazi** [comment]
issue 1 resolved
