### ISSUE TITLE
cleaner code

### ISSUE THREAD

**Issue by akhilsuseelan1996** [sheebashibushazi/testsection1#3]
https://github.com/sheebashibushazi/testsection1/blob/7e9a7ad7ea2357298b6e31b297fb77027623561f/TestExercise.java#L26

You can also implement in this way as well!
`ArrayList<Product> list=new ArrayList<>();
list.add(new Product(1,"desc1",1200,"Titan"));
`
Can you also remove the commented lines, please?

**Comment by sheebashibushazi** [comment]
resolved issue 3 
made code clean and concise
